[files]
extend-exclude = [
	"build-*/",
	"build/",
	"data/countryflags",
	"data/languages",
	"data/skins",
	"ddnet-libs",
	"other/icons/*.icns",
	"memcheck.supp",
	"scripts/android/files/res",
	"src/engine/external",

	# tests with invalid words
	"src/test/windows_test.cpp",
	"src/test/str_test.cpp",
]

[default]
extend-ignore-re = [
	# ddnet++
	'einZug-',
	'hax0r',
	'einFISCH',
	'hax',
	'hax_me_admin_mummy',
	'vor', # TODO: remove german comments
	'ein',
	'als',
	'ende',
	'effekt',
	'ist',
	'oder',
	'alle',
	'IST',
	'linke',
	'deine',
	'unter',
	'normale',
	'toleranz',
	'plattform',
	'dran',
	'passt',
	'sie',
	# funny english
	'mede',
	# bam
	'rc /fo',

	# ddnet
	'lod',
	'LOD',
	'Lod',
	'PARM',
	'PNGs',
	'SEH',
	'UPnP',
	'Datas',
	'datas',
	'iy',
	'cl_nameplates_ids_seperate_line',
	'0x510E527FUL',
	'I\*\*nteger',
	's\*\*tring',
]
